$(document).ready(function(){
	$("#ocultar4").click(function(evento){
		evento.preventDefault();
		$("#ocultar5").hide(1000);
   });
	$("#mostrar4").click(function(evento){
		evento.preventDefault();
		$("#ocultar5").show(1000);
   });
});
